clientbus:
  jwt:
    # YOUR_BASE64_SECRET_KEY
    secret: FnQHtz4yCzaBgma1a25xV30mShdAQZx/33msarZ57f0=
    expiration: 1800000

  bootstrap:
    organization:
      name: Penny Kit's Company ©
      email: admin@admin.admin
      username: admin
      password: admin
      firstname: Penny
      lastname: Kit
      phone: +12.04.1961(YAG)

  storage:
    local-path: D:\clientbus\storage

  kafka:
    outbound:
      enabled-channels:
        - TELEGRAM
        - WHATSAPP
        - VK




server:
#  servlet:
#    context-path: /clientbus

# logging:
  # level:
    # org.springframework.web: DEBUG
    # org.springdoc: DEBUG
    # org.springframework.boot.autoconfigure: DEBUG

springdoc:
  # Основные настройки
  api-docs:
    enabled: true
    path: /v3/api-docs
    # Формат вывода: json или yaml (по умолчанию json)

  swagger-ui:
    enabled: true
    path: /index.html

    # Дополнительные настройки UI
    display-request-duration: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
    doc-expansion: none

  # Пакеты для сканирования
  packages-to-scan:
    - kit.penny.clientbus.server.controller
#    - kit.penny.clientbus.server.security.controller

  # Пути для сканирования (если нужно)
  paths-to-match:
    - /api/**
    - /v3/**

  # Параметры по умолчанию
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

  # Кэширование
  cache:
    disabled: false

spring:
  application:
    name: server

  datasource:
    url: jdbc:postgresql://localhost:5432/clientbus
    username: clientbus
    password: clientbus

    hikari:
      schema: dbo

  session:
    jdbc:
      initialize-schema: never
      table-name: system.SPRING_SESSION

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer

    consumer:
      group-id: clientbus.inbound.processor
#  security:
#    user:
#      name: clientbus
#      password: clientbus

  jpa:
    hibernate:
      ddl-auto: update

    open-in-view: false

    properties:
      hibernate:
        default_schema: dbo
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: dbo,system
    default-schema: system
    create-schemas: true
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true
    table: flyway_schema_history